env:
  browser: true
  commonjs: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  # Possible Errors
  no-cond-assign:                                     # 禁止条件表达式中出现赋值操作符
    - error
    - always
  no-constant-condition:                              # 禁止在条件中使用常量表达式
    - error
    - checkLoops: true
  no-dupe-args: error                                 # 禁止 function 定义中出现重名参数
  no-dupe-keys: error                                 # 禁止对象字面量中出现重复的 key
  no-duplicate-case: error                            # 禁止出现重复的 case 标签
  no-ex-assign: error                                 # 禁止对 catch 子句的参数重新赋值
  no-extra-boolean-cast: error                        # 禁止不必要的布尔转换
  no-extra-semi: error                                # 禁止不必要的分号
  no-func-assign: error                               # 禁止对 function 声明重新赋值
  no-inner-declarations: error                        # 禁止在嵌套的块中出现变量声明或 function 声明
  no-invalid-regexp: error                            # 禁止 RegExp 构造函数中存在无效的正则表达式字符串
  no-obj-calls: error                                 # 禁止把全局对象作为函数调用
  no-prototype-builtins: error                        # 禁止直接调用 Object.prototypes 的内置属性
  no-sparse-arrays: error                             # 禁用稀疏数组
  no-unexpected-multiline: error                      # 禁止出现令人困惑的多行表达式
  use-isnan: error                                    # 要求使用 isNaN() 检查 NaN
  valid-typeof: error                                 # 强制 typeof 表达式与有效的字符串进行比较
  # Best Practices
  block-scoped-var: error                             # 强制把变量的使用限制在其定义的作用域范围内
  dot-location:                                       # 强制在点号之前和之后一致的换行
    - error
    - property
  eqeqeq:                                             # 要求使用 === 和 !==
    - error
    - always
  no-empty-function: error                            # 禁止出现空函数
  no-eval: error                                      # 禁用 eval()
  no-new-func: error                                  # 禁止对 Function 对象使用 new 操作符
  no-new-wrappers: error                              # 禁止对 String，Number 和 Boolean 使用 new 操作符
  no-param-reassign: error                            # 禁止对 function 的参数进行重新赋值
  no-redeclare: error                                 # 禁止多次声明同一变量
  no-script-url: error                                # 禁止使用 javascript: url
  no-self-assign: error                               # 禁止自我赋值
  no-self-compare: error                              # 禁止自身比较
  no-sequences: error                                 # 禁用逗号操作符
  # Variables
  no-delete-var: error                                # 禁止删除变量
  # Node.js and CommonJS
  no-new-require: error                               # 禁止调用 require 时使用 new 操作符
  # Stylistic Issues
  array-bracket-spacing: error                        # 强制数组方括号中使用一致的空格
  block-spacing: error                                # 强制在单行代码块中使用一致的空格
  brace-style: error                                  # 强制在代码块中使用一致的大括号风格
  comma-dangle:                                       # 要求或禁止末尾逗号
    - error
    - never
  comma-spacing: error                                # 强制在逗号前后使用一致的空格
  indent:                                             # 强制使用一致的缩进
    - error
    - 2
    - SwitchCase: 1
  jsx-quotes: error                                   # 强制在 JSX 属性中一致地使用双引号或单引号
  key-spacing:                                        # 强制在对象字面量的属性中键和值之间使用一致的间距
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing: off                                # 强制在关键字前后使用一致的空格
  no-mixed-operators: error                           # 禁止混合使用不同的操作符
  no-mixed-spaces-and-tabs: error                     # 禁止空格和 tab 的混合缩进
  no-multiple-empty-lines:                            # 禁止出现多行空行
    - error
    - max: 3
      maxEOF: 0
      maxBOF: 0
  no-trailing-spaces:                                 # 禁用行尾空格
    - error
    - skipBlankLines: true
      ignoreComments: true
  no-whitespace-before-property: error                # 禁止属性前有空白
  object-curly-spacing:                               # 强制在大括号中使用一致的空格
    - error
    - always
  operator-linebreak:                                 # 强制操作符使用一致的换行符
    - error
    - before
  quotes:                                             # 强制使用一致的反勾号、双引号或单引号
    - error
    - single
  semi:                                               # 要求或禁止使用分号代替 ASI
    - error
    - always
  space-before-blocks:                                # 强制在块之前使用一致的空格
    - error
    - never
  space-before-function-paren:                        # 强制在 function的左括号之前使用一致的空格
    - error
    - never
  space-infix-ops: error                              # 要求操作符周围有空格
  spaced-comment: error                               # 强制在注释中 // 或 /* 使用一致的空格
  # ECMAScript 6
  arrow-parens:                                       # 要求箭头函数的参数使用圆括号
    - error
    - always
  constructor-super: error                            # 要求在构造函数中有 super() 的调用
  no-this-before-super: error                         # 禁止在构造函数中，在调用 super() 之前使用 this 或 super
  no-var: error                                       # 要求使用 let 或 const 而不是 var
  prefer-const: error                                 # 要求使用 const 声明那些声明后不再被修改的变量
  object-shorthand: error                             # 要求或禁止对象字面量中方法和属性使用简写语法
  require-yield: error                                # 要求 generator 函数内有 yield
  template-curly-spacing:                             # 要求或禁止模板字符串中的嵌入表达式周围空格的使用
    - error
    - always
  # React
  react/button-has-type: error                        # 禁止<button>元素没有显式的"type"属性
  react/prefer-es6-class:                             # 使用ES5创建反应类模块或新的ES6类系统
    - error
    - always
  # JSX
  react/jsx-boolean-value:                            # 在JSX中使用布尔属性时，可以将属性值设置为true或省略值
    - error
    - always
  react/jsx-closing-tag-location: error               # 验证JSX中的结束标签位置
  react/jsx-equals-spacing: error                     # 强制或禁止JSX属性中的等号周围的空格
  react/jsx-first-prop-new-line:                      # 此规则检查所有JSX元素的第一个属性是否正确放置
    - error
    - never
  react/jsx-indent:                                   # 验证JSX缩进
    - error
    - 2
  react/jsx-indent-props:                             # 验证JSX中props的缩进
    - error
    - 2
  react/jsx-key: error                                # 在数组或迭代器中验证JSX具有key属性
  react/jsx-no-comment-textnodes: error               # 防止将注释插入为文本节点
  react/jsx-no-duplicate-props: error                 # 在JSX中防止重复的props
  react/jsx-curly-brace-presence:                     # 强制使用大括号或不使用不必要的大括号
    - error
    - never
  react/jsx-tag-spacing:                              # 验证JSX左右括号中的空格
    - error
    - closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: never
  # flow
  flowtype/boolean-style:                             # 强制布尔类型注释的特定样式
    - error
    - boolean
  flowtype/delimiter-dangle:                          # 强制在Object和Tuple注释中一致使用尾随逗号
    - error
    - never
  flowtype/generic-spacing: error                     # 在泛型类型注释参数中强制保持一致的间距
  flowtype/no-dupe-keys: error                        # 检查对象注释中的重复属性
  flowtype/no-primitive-constructor-types: error      # 不允许使用基本构造函数作为类型，如Boolean，Number和String
  flowtype/object-type-delimiter:                     # 强制Flow对象类型中的属性之间保持一致的分隔符
    - error
    - comma
  flowtype/require-parameter-type: error              # 要求所有的函数参数都有类型注释
  flowtype/require-return-type:                       # 要求该函数具有返回类型注释
    - error
    - always
    - annotateUndefined: always
  flowtype/require-variable-type: error               # 要求所有变量声明符都有类型注释
  flowtype/semi: error                                # 在类型别名后强制使用分号
  flowtype/space-after-type-colon: error              # 在类型注释冒号后强制一致的间距
  flowtype/space-before-generic-bracket: error        # 在泛型类型注释参数之前强制一致的间距
  flowtype/space-before-type-colon: error             # 在类型注释冒号之前强制一致的间距
  flowtype/union-intersection-spacing: error          # 在联合和相交类型分隔符周围实施一致的间距